version: "3"

services:

  networksandbox:
    image: k8s.gcr.io/pause

  obs:
    privileged: true
    network_mode: "service:networksandbox"
    ipc: host
    build:
      context: obs-studio
      dockerfile: Dockerfile.ubuntu
    environment:
    - DISPLAY
    - HOME
    - USER
    volumes:
    #- /tmp/.X11-unix/:/tmp/.X11-unix/
    - /srv/dev-disk-by-id-ata-CT120BX500SSD1_1921E1843F57-part4/docker-apps/obs-studio:$HOME/.config/obs-studio
    #- $HOME/.fonts/:$HOME/.fonts/
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /etc/group:/etc/group:ro
   #- $HOME/Downloads:$HOME/Downloads
    #- /run/user/$UID/pulse/:/var/run/pulse/
    #- ./data/:/data/
    - /usr/lib/x86_64-linux-gnu/:/local-libraries/:ro
    command:
    - sh
    - -c
    - |
      chown ${UID:1001} $HOME/.config/obs-studio
      chown ${UID:1001} $HOME
      xset -dpms
      xset s off
      if [ -d /local-libraries ]; then
        cp -a /local-libraries/libnv* /usr/lib/x86_64-linux-gnu/
        cp -a /local-libraries/nvidia/current/* /usr/lib/x86_64-linux-gnu/
      fi
      mkdir -p $HOME/.config/obs-studio/plugins
      [ -d $HOME/.config/obs-studio/plugins/obs-linuxbrowser ] ||
        ln -sf /src/obs-linuxbrowser $HOME/.config/obs-studio/plugins/obs-linuxbrowser
      exec su $USER sh -c "exec obs"
